### ISSUE TITLE
Latest code fails with error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by larryclaman** [Azure/container-scan#132]
I'm trying the latest code from PR #29 but the action is failing with an error:

```
Run azure/container-scan@b5317f7365a8e3aab8e35d97e932d105ad2ed4e8
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/azure/container-scan/b5317f7365a8e3aab8e35d97e932d105ad2ed4e8/lib/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/azure/container-scan/b5317f7365a8e3aab8e35d97e932d105ad2ed4e8/lib/main.js:19:27)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:[14](https://github.com/xxx/xxx/runs/5072317271?check_suite_focus=true#step:4:14))
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/azure/container-scan/b53[17](https://github.com/xxx/xxx/runs/5072317271?check_suite_focus=true#step:4:17)f7365a8e3aab8e35d97e9[32](https://github.com/xxx/xxx/runs/5072317271?check_suite_focus=true#step:4:32)d105ad2ed4e8/lib/main.js'
  ]
}
```

**Comment by joshuanianji** [comment]
I had the same issue as I was using hashes to reference the package, but I switched to using `azure/container-scan@v0.1` and it worked. Not sure why it wasn't working with the hashes, though.

The devs updated the binaries for `v0.1` and `v0`, so using those still work.

**Comment by koushdey** [comment]
@larryclaman Can you refer to the comment from @joshuanianji ? ☝🏾

**Comment by larryclaman** [comment]
Understood....I had (mistakenly) assumed that when this bug was fixed, the version number would be bumped to reflect the change.    (I also had not noticed that the tagged releases V0 and v0.1 are on a separate release branch, not the master branch).  

Not how I would have done it (I would have bumped the release number) but <shrug>, I guess it works, except that the date shown on the **releases** page does not reflect the latest update (See screenshot)


![Screenshot 2022-02-07 075749](https://user-images.githubusercontent.com/25161683/152792818-7bb7d687-c209-4edc-88e5-f8538b3355fe.png)
